name: flutter_application_1
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  image_picker: ^1.1.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_animate: ^4.3.0
  signature: ^5.4.0
  path_provider: ^2.1.2
  pdf: ^3.11.0
  printing: ^5.12.0
  iconsax: ^0.0.8
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ojt.png
    - assets/images/logo.gif





